version: "3.5"
services:
  # Create a service named db.
  db:
    # Use the Docker Image postgres. This will pull the newest release.
    image: "postgres"
    # Give the container the name my_postgres. You can changes to something else.
    container_name: "anuncios_backend_db"
    # Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER=${APP_DB_USERNAME}
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD}
      - POSTGRES_DB=${APP_DB_NAME}
    # Maps port 54320 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "${APP_DB_PORT}:5432"
    # Set a volume some that database is not lost after shutting down the container.
    # I used the name postgres-data but you can changed it to something else.
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  envoy:
    build:
      context: envoy
    ports:
      - "8080:8080"
      - "9901:9901"
    depends_on:
      - server
  server:
    build:
      context: .
  web:
    image: httpd:2.4
    volumes:
      - ${PWD}/web/web-client:/usr/local/apache2/htdocs/
    ports:
      - "8060:80"
    depends_on:
      - envoy
networks:
  backend: